# Generated by Django 3.0.3 on 2020-02-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(blank=True, default='add series title', max_length=200, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PassageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_title_text', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('series', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=200)),
                ('passage_text', models.CharField(blank=True, max_length=1000)),
                ('day_by_day_question_text', models.CharField(blank=True, max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('passage_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PassageTitle')),
            ],
        ),
    ]
