# Generated by Django 3.0.3 on 2020-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='day_by_day_question_text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='passage_text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
