# Generated by Django 3.0.3 on 2020-02-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200228_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='day_by_day_question_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='passage_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Series'),
            preserve_default=False,
        ),
    ]
