# Generated by Django 3.0.3 on 2020-02-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200228_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_title',
            field=models.CharField(blank=True, default='add series title', max_length=200, null=True),
        ),
    ]
